function [BW, maskedRGBImage] = ch02_createMask_generated(RGB)
%CH02_CREATEMASK_GENERATED 門檻化 RGB 影像。
%
%  這支函式**原封不動**保留 Color Thresholder APP「匯出 > 產生函式」的輸出，
%  只改了函式名稱。刻意不整理，是為了讓你看清楚 APP 產生的程式碼長什麼樣子，
%  以及為什麼它不能就這樣拿去用。
%
%  觀察重點：
%    · 每個門檻都是寫死的數字，沒有任何一個可以從外面調整
%    · 變數命名是 channel1Min / channel2Max，看不出是色相還是飽和度
%    · 沒有輸入驗證，丟灰階影像進去會直接壞掉
%    · 沒有說明哪一組門檻對應哪一種顏色
%
%  第 02 章的第 ③ 步就是把它重構成 ch02_findChips，解決以上每一個問題。
%
%  另見 CH02_FINDCHIPS, COLORTHRESHOLDER.

% Auto-generated by colorThresholder app on 16-Sep-2026
%------------------------------------------------------

% Convert RGB image to chosen color space
I = rgb2hsv(RGB);

% Define thresholds for channel 1 based on histogram settings
channel1Min = 0.900;
channel1Max = 0.040;

% Define thresholds for channel 2 based on histogram settings
channel2Min = 0.450;
channel2Max = 1.000;

% Define thresholds for channel 3 based on histogram settings
channel3Min = 0.300;
channel3Max = 1.000;

% Create mask based on chosen histogram thresholds
sliderBW = ( (I(:,:,1) >= channel1Min) | (I(:,:,1) <= channel1Max) ) & ...
    (I(:,:,2) >= channel2Min ) & (I(:,:,2) <= channel2Max) & ...
    (I(:,:,3) >= channel3Min ) & (I(:,:,3) <= channel3Max);
BW = sliderBW;

% Initialize output masked image based on input image.
maskedRGBImage = RGB;

% Set background pixels where BW is false to zero.
maskedRGBImage(repmat(~BW,[1 1 3])) = 0;

end
